"""add task_id to articles

Revision ID: 20260318
Revises: c619ab9ba95a
Create Date: 2026-03-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260318'
down_revision: Union[str, None] = 'c619ab9ba95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index('idx_articles_task_status', 'articles', ['task_id', 'persist_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_task_status', table_name='articles')
    op.drop_column('articles', 'task_id')
    # ### end Alembic commands ###
