# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2026 Weaver Contributors
"""Extend daily_briefings for per-category briefings (T004).

Revision ID: 32_extend_daily_briefings_for_category
Revises: 31_add_sentiment_shifts_article_index
Create Date: 2026-07-17

Changes:
- daily_briefings: add category (VARCHAR(20), nullable)
- daily_briefings: drop single-column UNIQUE on briefing_date
- daily_briefings: add composite UNIQUE(briefing_date, category)

Background:
- Existing daily_briefings.briefing_date is UNIQUE, blocking multiple
  briefings per day.
- T004 BriefingGenerator produces 4 briefings per day (finance/tech/ai/
  general per spec R-briefing-003).
- Migration 32 drops the single-column unique, adds category column
  (nullable for backward compat with existing rows), and creates a
  composite UNIQUE(briefing_date, category).
- PostgreSQL treats NULL as distinct in UNIQUE constraints, so existing
  rows with category=NULL remain valid after upgrade.

Downgrade safety:
- Downgrade drops the composite unique, drops the category column, and
  restores the single-column UNIQUE on briefing_date. If multiple rows
  with the same briefing_date exist (e.g. 4 categories per day after
  upgrade), downgrade will FAIL with a unique violation — this is
  intentional (Rule 12 — fail loud). Operators must DELETE duplicate
  rows before downgrading. A pre-downgrade check is included that raises
  RuntimeError if duplicate briefing_date rows are detected.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import context, op

revision: str = "32_extend_daily_briefings_for_category"
down_revision: str | None = "31_add_sentiment_shifts_article_index"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add category column + replace single unique with composite unique."""
    # Step 1: Add category column (nullable for backward compat).
    op.add_column(
        "daily_briefings",
        sa.Column("category", sa.String(20), nullable=True),
    )

    # Step 2: Drop the single-column unique constraint on briefing_date.
    # Name auto-generated by SQLAlchemy as daily_briefings_briefing_date_key
    # (from sa.Column(..., unique=True) in migration 04_create_analytics_tables).
    # Use IF EXISTS for robustness — name may vary across installations.
    op.execute(
        "ALTER TABLE daily_briefings DROP CONSTRAINT IF EXISTS daily_briefings_briefing_date_key"
    )

    # Step 3: Create composite UNIQUE(briefing_date, category).
    # Allows up to 4 briefings per day (one per category). NULL category
    # treated as distinct by PostgreSQL, so pre-migration rows remain valid.
    op.create_unique_constraint(
        "uq_briefings_date_category",
        "daily_briefings",
        ["briefing_date", "category"],
    )


def downgrade() -> None:
    """Reverse: drop composite unique, drop category, restore single unique.

    Raises:
        RuntimeError: If duplicate briefing_date rows exist (e.g. 4 categories
            per day). Operator must DELETE duplicates before downgrading —
            automatically picking one would silently lose data (Rule 12).

    """
    # Pre-downgrade safety check: detect duplicate briefing_date rows.
    # If found, refuse to downgrade — operator must choose which rows to keep.
    # Skip in offline SQL mode (sql=True) — bind.execute() returns None in
    # offline mode (SQL is emitted to stdout but not actually executed), so
    # the check is impossible. Operators running offline downgrades must
    # pre-check for duplicates manually.
    if not context.is_offline_mode():
        bind = op.get_bind()
        duplicates = bind.execute(
            sa.text(
                "SELECT briefing_date, COUNT(*) FROM daily_briefings "
                "GROUP BY briefing_date HAVING COUNT(*) > 1"
            )
        ).fetchall()
        if duplicates:
            dates = [str(row[0]) for row in duplicates]
            raise RuntimeError(
                f"Cannot downgrade migration 32: {len(duplicates)} briefing_date(s) "
                f"have multiple rows ({dates[:3]}...). Multiple briefings per day "
                f"exist (e.g. finance/tech/ai/general). Delete duplicate rows "
                f"before downgrading — automatic deletion would silently lose data."
            )

    # Step 1: Drop composite unique.
    op.drop_constraint("uq_briefings_date_category", "daily_briefings", type_="unique")

    # Step 2: Drop category column.
    op.drop_column("daily_briefings", "category")

    # Step 3: Restore single-column unique on briefing_date.
    op.create_unique_constraint(
        "daily_briefings_briefing_date_key",
        "daily_briefings",
        ["briefing_date"],
    )
