"""add quality_score to articles

Revision ID: c619ab9ba95a
Revises: 20260313
Create Date: 2026-03-17 03:24:59.462273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c619ab9ba95a'
down_revision: Union[str, None] = '20260313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add updated_at column to article_vectors if it doesn't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'article_vectors' AND column_name = 'updated_at'
            ) THEN
                ALTER TABLE article_vectors ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
            END IF;
        END $$;
    """)
    # Fill null values for updated_at before setting NOT NULL
    op.execute("""
        UPDATE article_vectors 
        SET updated_at = NOW() 
        WHERE updated_at IS NULL
    """)
    op.alter_column('article_vectors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('articles', sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.drop_index(op.f('idx_articles_processing_stage'), table_name='articles')
    op.drop_index(op.f('idx_articles_retry_count'), table_name='articles')
    op.drop_index(op.f('idx_articles_credibility'), table_name='articles')
    op.create_index('idx_articles_credibility', 'articles', [sa.literal_column('credibility_score DESC')], unique=False)
    op.drop_index(op.f('idx_articles_publish_time'), table_name='articles')
    op.create_index('idx_articles_publish_time', 'articles', [sa.literal_column('publish_time DESC')], unique=False)
    op.drop_index(op.f('idx_articles_score'), table_name='articles')
    op.create_index('idx_articles_score', 'articles', [sa.literal_column('score DESC')], unique=False)
    op.drop_index(op.f('idx_articles_sentiment_score'), table_name='articles')
    op.create_index('idx_articles_sentiment_score', 'articles', [sa.literal_column('sentiment_score DESC')], unique=False)
    op.create_index('idx_articles_category_publish', 'articles', ['category', sa.literal_column('publish_time DESC')], unique=False)
    op.create_index('idx_articles_host_publish', 'articles', ['source_host', sa.literal_column('publish_time DESC')], unique=False)
    op.create_index('idx_articles_persist_status', 'articles', ['persist_status'], unique=False, postgresql_where=sa.text("persist_status IN ('pending', 'pg_done')"))
    op.create_index('idx_articles_status_created', 'articles', ['persist_status', sa.literal_column('created_at ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_status_created', table_name='articles')
    op.drop_index('idx_articles_persist_status', table_name='articles', postgresql_where=sa.text("persist_status IN ('pending', 'pg_done')"))
    op.drop_index('idx_articles_host_publish', table_name='articles')
    op.drop_index('idx_articles_category_publish', table_name='articles')
    op.drop_index('idx_articles_sentiment_score', table_name='articles')
    op.create_index(op.f('idx_articles_sentiment_score'), 'articles', ['sentiment_score'], unique=False)
    op.drop_index('idx_articles_score', table_name='articles')
    op.create_index(op.f('idx_articles_score'), 'articles', ['score'], unique=False)
    op.drop_index('idx_articles_publish_time', table_name='articles')
    op.create_index(op.f('idx_articles_publish_time'), 'articles', ['publish_time'], unique=False)
    op.drop_index('idx_articles_credibility', table_name='articles')
    op.create_index(op.f('idx_articles_credibility'), 'articles', ['credibility_score'], unique=False)
    op.create_index(op.f('idx_articles_retry_count'), 'articles', ['retry_count'], unique=False)
    op.create_index(op.f('idx_articles_processing_stage'), 'articles', ['processing_stage'], unique=False)
    op.drop_column('articles', 'quality_score')
    op.alter_column('article_vectors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
